// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

// TODO
// Make a function which adds two numbers - to generate the next Fibonacci number
// Find a way to keep it going until the limit (4 million) - probably a loop
// Identifying even numbers
// Some functionality to add the numbers together
// Print output at end

function isEven(num) {
  return num % 2 === 0
}

function main() {
  let evenSum = 0
  let fNumber1 = 0
  let fNumber2 = 1
  const limitNumber = 4000000

  while (fNumber2 < limitNumber) {
    if (isEven(fNumber2)) {
      evenSum += fNumber2
    }
    let nextFnumber = fNumber1 + fNumber2
    fNumber1 = fNumber2
    fNumber2 = nextFnumber
  }
  console.log(evenSum)
}
main()
